version: "3.6"

services:
  fd-api-orders:
    build: .
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    container_name: fd-api-orders
    restart: on-failure
    ports:
      - "3000:3000"