version: "3.6"

services:
  fd-api-orders:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    container_name: fd-api-orders
    restart: on-failure
    ports:
      - 3300:3300